import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Privacy Policy — MiddleDoc',
  description: 'How MiddleDoc collects, uses, and protects your personal data.',
}

export default function PrivacyPolicyPage() {
  return (
    <article className="prose prose-neutral max-w-none prose-headings:font-semibold prose-headings:text-neutral-900 prose-p:text-neutral-700 prose-li:text-neutral-700 prose-a:text-primary-600">
      <h1>Privacy Policy</h1>
      <p className="text-sm text-neutral-500">Effective Date: June 30, 2026 &nbsp;|&nbsp; Last Updated: June 30, 2026</p>

      <p>
        MiddleDoc (&ldquo;MiddleDoc,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;) operates the document collection and
        e-signature platform available at <strong>middledoc.com</strong> (the &ldquo;Service&rdquo;). This Privacy
        Policy explains what personal data we collect, how we use and share it, and what rights
        you have over your data. By using the Service you agree to the practices described here.
      </p>
      <p>
        If you are a business customer using MiddleDoc to collect documents from your own clients,
        you are a &ldquo;data controller&rdquo; and MiddleDoc acts as your &ldquo;data processor.&rdquo; Our Data
        Processing Agreement (DPA), available at middledoc.com/legal/dpa, governs that
        relationship and supplements this Policy.
      </p>

      <hr />

      <h2>1. Who We Are</h2>
      <p>
        MiddleDoc is a software-as-a-service company founded in 2026. Our registered contact
        address for privacy matters is:
      </p>
      <address className="not-italic">
        MiddleDoc<br />
        Privacy Team<br />
        Email: <a href="mailto:hello@middledoc.com">hello@middledoc.com</a>
      </address>

      <hr />

      <h2>2. Data We Collect</h2>

      <h3>2.1 Account Information</h3>
      <p>When you create a MiddleDoc account we collect:</p>
      <ul>
        <li>Full name and email address</li>
        <li>Password (stored as a bcrypt hash — we never store plaintext passwords)</li>
        <li>Company or firm name (optional)</li>
        <li>Subscription plan and billing tier</li>
        <li>Account creation date and last login timestamp</li>
      </ul>

      <h3>2.2 Documents and Files You Upload</h3>
      <p>
        MiddleDoc is a document collection platform. When you or your clients upload files through
        the Service we receive and store:
      </p>
      <ul>
        <li>The document files themselves (PDFs, images, spreadsheets, and other formats you submit)</li>
        <li>File metadata: filename, size, MIME type, upload timestamp, uploader IP address</li>
        <li>AI classification results generated by our document recognition feature (document type labels such as &ldquo;W-2,&rdquo; &ldquo;Invoice,&rdquo; &ldquo;Bank Statement,&rdquo; etc.)</li>
        <li>E-signature audit trail data: signer name, email, IP address, timestamp, and signature image</li>
        <li>Document request status and checklist completion data</li>
      </ul>
      <p>
        <strong>Important:</strong> MiddleDoc does not control what documents you or your clients upload.
        If you upload documents containing special-category personal data (health records, financial
        data, identity documents), you are responsible for ensuring you have the right to process
        and share that data with us.
      </p>

      <h3>2.3 Usage Data</h3>
      <p>We automatically collect technical information when you use the Service:</p>
      <ul>
        <li>IP address and approximate geographic location (country/region)</li>
        <li>Browser type, operating system, and device type</li>
        <li>Pages visited within the Service, feature interactions, and session duration</li>
        <li>HTTP request logs (method, URL path, response code, response time)</li>
        <li>Error logs and crash reports</li>
      </ul>
      <p>
        We do <strong>not</strong> use Google Analytics or any third-party behavioral tracking
        scripts. Usage data is collected from our own server logs and infrastructure only.
      </p>

      <h3>2.4 Payment Information</h3>
      <p>
        We do not store your credit card numbers or full payment credentials on our servers.
        Payments are processed by Stripe (for US and international customers) and Paystack (for
        customers in Africa). These processors store payment instrument data under their own PCI
        DSS compliant environments. We receive only tokenized payment identifiers, subscription
        status, and billing history metadata.
      </p>

      <h3>2.5 Client Contact Data You Provide</h3>
      <p>
        When MiddleDoc account holders add clients to the platform (for document request
        management), they provide client names and email addresses. This data is stored on our
        behalf and governed by the DPA when the account holder is acting as a data controller.
      </p>

      <h3>2.6 Communication Data</h3>
      <p>
        When you contact us by email, we retain the contents of that correspondence including your
        email address, subject matter, and any attachments you send, for the purpose of resolving
        your inquiry.
      </p>

      <hr />

      <h2>3. How We Use Your Data</h2>

      <table className="w-full text-sm border-collapse">
        <thead>
          <tr className="bg-neutral-50">
            <th className="text-left p-3 border border-neutral-200 font-semibold">Purpose</th>
            <th className="text-left p-3 border border-neutral-200 font-semibold">Legal Basis (GDPR)</th>
          </tr>
        </thead>
        <tbody>
          {[
            ['Providing the Service: creating accounts, processing document uploads, generating e-signatures, sending email reminders', 'Performance of contract (Art. 6(1)(b))'],
            ['AI document classification: sending document content to OpenAI or Anthropic APIs to generate classification labels', 'Performance of contract (Art. 6(1)(b))'],
            ['Payment processing: collecting subscription fees through Stripe or Paystack', 'Performance of contract (Art. 6(1)(b))'],
            ['Sending transactional emails: upload confirmations, document request notifications, password resets, billing receipts via SendGrid', 'Performance of contract (Art. 6(1)(b))'],
            ['Security and fraud prevention: detecting abuse, rate limiting, IP-based access controls', 'Legitimate interests (Art. 6(1)(f))'],
            ['Service improvement: analyzing aggregated, de-identified usage patterns to improve product features', 'Legitimate interests (Art. 6(1)(f))'],
            ['Legal compliance: retaining records as required by applicable law, responding to lawful government requests', 'Legal obligation (Art. 6(1)(c))'],
            ['Customer support: responding to your inquiries and resolving disputes', 'Legitimate interests (Art. 6(1)(f))'],
          ].map(([purpose, basis], i) => (
            <tr key={i} className={i % 2 === 0 ? 'bg-white' : 'bg-neutral-50'}>
              <td className="p-3 border border-neutral-200">{purpose}</td>
              <td className="p-3 border border-neutral-200 text-neutral-500">{basis}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <p className="mt-4">
        We do not sell your personal data. We do not use your personal data for advertising
        purposes or share it with ad networks.
      </p>

      <hr />

      <h2>4. Third-Party Service Providers (Sub-Processors)</h2>
      <p>
        We share data with the following sub-processors strictly to operate the Service. Each is
        bound by contractual data protection obligations.
      </p>

      <table className="w-full text-sm border-collapse">
        <thead>
          <tr className="bg-neutral-50">
            <th className="text-left p-3 border border-neutral-200 font-semibold">Provider</th>
            <th className="text-left p-3 border border-neutral-200 font-semibold">Purpose</th>
            <th className="text-left p-3 border border-neutral-200 font-semibold">Data Shared</th>
            <th className="text-left p-3 border border-neutral-200 font-semibold">Location</th>
          </tr>
        </thead>
        <tbody>
          {[
            ['Cloudflare, Inc.', 'CDN, DNS, DDoS protection, document storage (R2)', 'All traffic passing through middledoc.com; uploaded files', 'USA (global edge)'],
            ['Render Services, Inc.', 'Application and API hosting', 'All application data processed by our servers', 'USA'],
            ['OpenAI, L.L.C.', 'AI document classification', 'Document content submitted for classification', 'USA'],
            ['Anthropic, PBC', 'AI document classification (alternative provider)', 'Document content submitted for classification', 'USA'],
            ['Twilio (SendGrid)', 'Transactional email delivery', 'Recipient email address, email subject and body', 'USA'],
            ['Stripe, Inc.', 'Payment processing (US/international)', 'Name, email, billing details (tokenized)', 'USA'],
            ['Paystack (Stripe subsidiary)', 'Payment processing (Africa)', 'Name, email, billing details (tokenized)', 'Nigeria / USA'],
            ['Supabase / PostgreSQL', 'Relational database', 'All structured account and metadata', 'USA'],
          ].map(([provider, purpose, data, location], i) => (
            <tr key={i} className={i % 2 === 0 ? 'bg-white' : 'bg-neutral-50'}>
              <td className="p-3 border border-neutral-200 font-medium">{provider}</td>
              <td className="p-3 border border-neutral-200">{purpose}</td>
              <td className="p-3 border border-neutral-200 text-neutral-600">{data}</td>
              <td className="p-3 border border-neutral-200 text-neutral-500">{location}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <p className="mt-4">
        <strong>AI Processing Note:</strong> When you use the AI document classification feature,
        the content of the document is transmitted to OpenAI or Anthropic for processing. These
        providers process data under API terms that restrict use of your data for training their
        models without explicit consent. We have configured our API integrations to use
        data-handling modes that prevent your documents from being used to train third-party AI
        models. However, you should exercise discretion before enabling AI classification on
        highly sensitive documents. You may disable AI classification on a per-request basis.
      </p>

      <hr />

      <h2>5. Data Retention</h2>

      <table className="w-full text-sm border-collapse">
        <thead>
          <tr className="bg-neutral-50">
            <th className="text-left p-3 border border-neutral-200 font-semibold">Data Category</th>
            <th className="text-left p-3 border border-neutral-200 font-semibold">Retention Period</th>
          </tr>
        </thead>
        <tbody>
          {[
            ['Account information (name, email, hashed password)', 'Duration of account plus 90 days after deletion request'],
            ['Uploaded documents and files', 'Duration of account; deleted within 30 days of account termination unless you export first'],
            ['E-signature audit trail records', '7 years from date of signing (legal requirement for enforceable signature records)'],
            ['Payment and billing records', '7 years (tax and accounting legal obligation)'],
            ['Server and access logs', '90 days rolling'],
            ['Email communication records (support)', '3 years'],
            ['AI classification results', 'Duration of account; deleted with associated document'],
          ].map(([category, period], i) => (
            <tr key={i} className={i % 2 === 0 ? 'bg-white' : 'bg-neutral-50'}>
              <td className="p-3 border border-neutral-200">{category}</td>
              <td className="p-3 border border-neutral-200 text-neutral-600">{period}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <p className="mt-4">
        When a retention period expires we securely delete or irreversibly anonymize the data.
        Backups are purged on a rolling 30-day cycle.
      </p>

      <hr />

      <h2>6. Your Rights (GDPR — EEA, UK, Switzerland)</h2>
      <p>
        If you are located in the European Economic Area, the United Kingdom, or Switzerland, you
        have the following rights under the General Data Protection Regulation (GDPR) or
        applicable national law:
      </p>
      <ul>
        <li>
          <strong>Right of access (Art. 15):</strong> You may request a copy of the personal data
          we hold about you, including the categories of data, the purposes of processing, and any
          third parties with whom we share it.
        </li>
        <li>
          <strong>Right to rectification (Art. 16):</strong> You may request that we correct
          inaccurate or incomplete personal data about you.
        </li>
        <li>
          <strong>Right to erasure / &ldquo;right to be forgotten&rdquo; (Art. 17):</strong> You may
          request deletion of your personal data when it is no longer necessary for the purposes
          for which it was collected, or where you have withdrawn consent. Note that certain data
          (e.g., e-signature audit trails, billing records) must be retained for legal compliance
          and cannot be deleted on request.
        </li>
        <li>
          <strong>Right to data portability (Art. 20):</strong> You may request your personal data
          in a structured, commonly used, machine-readable format (JSON or CSV). Log in to your
          account and navigate to Settings &gt; Account &gt; Export Data, or contact us at
          hello@middledoc.com.
        </li>
        <li>
          <strong>Right to restriction of processing (Art. 18):</strong> You may request that we
          restrict processing of your data in certain circumstances, such as when you contest the
          accuracy of the data.
        </li>
        <li>
          <strong>Right to object (Art. 21):</strong> You may object to processing based on our
          legitimate interests at any time. We will cease processing unless we demonstrate
          compelling legitimate grounds.
        </li>
        <li>
          <strong>Right to withdraw consent:</strong> Where processing is based on consent you may
          withdraw it at any time without affecting the lawfulness of prior processing.
        </li>
        <li>
          <strong>Right to lodge a complaint:</strong> You have the right to lodge a complaint
          with your national data protection supervisory authority. In the EU, you may contact the
          supervisory authority in the member state of your habitual residence.
        </li>
      </ul>
      <p>
        To exercise any of these rights, email <a href="mailto:hello@middledoc.com">hello@middledoc.com</a> with
        the subject line &ldquo;Data Rights Request&rdquo; and a description of your request. We will
        respond within 30 days. We may ask you to verify your identity before acting on your
        request.
      </p>

      <hr />

      <h2>7. California Privacy Rights (CCPA / CPRA)</h2>
      <p>
        If you are a California resident, the California Consumer Privacy Act (CCPA) as amended
        by the California Privacy Rights Act (CPRA) grants you additional rights.
      </p>

      <h3>7.1 Categories of Personal Information Collected</h3>
      <p>In the preceding 12 months we have collected the following CCPA categories of personal information:</p>
      <ul>
        <li><strong>Identifiers:</strong> Name, email address, IP address, account ID</li>
        <li><strong>Commercial information:</strong> Subscription plan, billing history</li>
        <li><strong>Internet or other electronic network activity:</strong> Usage logs, feature interactions</li>
        <li><strong>Professional or employment-related information:</strong> Firm name (if provided)</li>
        <li><strong>Inferences:</strong> Account activity patterns used for service improvement (not for profiling)</li>
        <li><strong>Sensitive Personal Information:</strong> The contents of documents you upload may contain sensitive information. We process this solely to provide the Service.</li>
      </ul>

      <h3>7.2 Your CCPA Rights</h3>
      <ul>
        <li><strong>Right to Know:</strong> You may request disclosure of the personal information we collect, use, disclose, and sell.</li>
        <li><strong>Right to Delete:</strong> You may request deletion of your personal information, subject to certain exceptions.</li>
        <li><strong>Right to Correct:</strong> You may request correction of inaccurate personal information.</li>
        <li><strong>Right to Opt-Out of Sale or Sharing:</strong> We do <strong>not</strong> sell or share your personal information for cross-context behavioral advertising. No opt-out is necessary.</li>
        <li><strong>Right to Limit Use of Sensitive Personal Information:</strong> We use sensitive personal information only to provide the Service, not for profiling or advertising.</li>
        <li><strong>Non-Discrimination:</strong> We will not discriminate against you for exercising your CCPA rights.</li>
      </ul>
      <p>
        To submit a CCPA request, email <a href="mailto:hello@middledoc.com">hello@middledoc.com</a> with
        the subject &ldquo;California Privacy Request.&rdquo; We will respond within 45 days (extendable
        by an additional 45 days with notice).
      </p>

      <hr />

      <h2>8. International Data Transfers</h2>
      <p>
        MiddleDoc is operated from the United States. If you access the Service from outside the
        United States, your data will be transferred to and processed in the United States, which
        may have data protection laws that differ from your country of residence.
      </p>
      <p>
        For transfers of personal data from the European Economic Area, the United Kingdom, or
        Switzerland to the United States, we rely on:
      </p>
      <ul>
        <li>
          <strong>Standard Contractual Clauses (SCCs):</strong> Our DPA incorporates the European
          Commission&apos;s approved Standard Contractual Clauses (June 2021 version) for
          controller-to-processor transfers.
        </li>
        <li>
          <strong>Adequacy decisions:</strong> Where available and applicable.
        </li>
        <li>
          <strong>UK International Data Transfer Agreements (IDTAs):</strong> For transfers
          involving UK data subjects.
        </li>
      </ul>
      <p>
        Our sub-processors that handle EEA/UK personal data have executed SCCs with us or
        participate in equivalent transfer mechanisms. A copy of our SCCs is available upon
        written request to <a href="mailto:hello@middledoc.com">hello@middledoc.com</a>.
      </p>

      <hr />

      <h2>9. Cookies and Tracking Technologies</h2>
      <p>
        MiddleDoc uses a minimal cookie approach. We set only one category of cookie:
      </p>
      <ul>
        <li>
          <strong>Session authentication cookie (httpOnly JWT):</strong> A single, httpOnly,
          Secure, SameSite=Strict cookie that stores your encrypted JSON Web Token (JWT)
          authentication credential. This cookie is strictly necessary to keep you logged in. It
          cannot be read by JavaScript and is not accessible to third parties.
        </li>
      </ul>
      <p>
        We do <strong>not</strong> set advertising cookies, third-party tracking cookies, analytics
        cookies (Google Analytics, Mixpanel, etc.), or persistent fingerprinting identifiers.
        Because we use only strictly necessary cookies, no cookie consent banner is technically
        required, but we provide full disclosure here and in our Cookie Policy at
        middledoc.com/legal/cookies.
      </p>

      <hr />

      <h2>10. Children&apos;s Privacy</h2>
      <p>
        The Service is not directed at individuals under 16 years of age. We do not knowingly
        collect personal data from children under 16. If you believe we have inadvertently
        collected data from a person under 16, please contact us immediately at
        hello@middledoc.com and we will delete that data promptly.
      </p>

      <hr />

      <h2>11. Security Measures</h2>
      <p>
        We implement industry-standard security measures to protect your personal data:
      </p>
      <ul>
        <li>All data in transit is encrypted using TLS 1.3</li>
        <li>Documents at rest are encrypted using AES-256 on Cloudflare R2</li>
        <li>Authentication uses bcrypt-hashed passwords and httpOnly JWT tokens</li>
        <li>Access to production systems is restricted to authorized personnel with MFA required</li>
        <li>We conduct regular security audits and remediate findings promptly</li>
        <li>Our infrastructure achieved a security rating of A- in independent auditing</li>
      </ul>
      <p>
        For full details see our Security Policy at middledoc.com/legal/security. No method of
        transmission over the internet or electronic storage is 100% secure. In the event of a
        data breach affecting your personal data we will notify you as required by applicable law.
      </p>

      <hr />

      <h2>12. Links to Third-Party Services</h2>
      <p>
        The Service may contain links to third-party websites or services (such as QuickBooks for
        integration). This Privacy Policy does not apply to those third-party services. We
        encourage you to review the privacy policies of any third-party services you access.
      </p>

      <hr />

      <h2>13. Changes to This Privacy Policy</h2>
      <p>
        We may update this Privacy Policy from time to time. When we make material changes we
        will notify you by email (to the address associated with your account) at least 14 days
        before the change takes effect, and we will update the &ldquo;Last Updated&rdquo; date at the top
        of this page. Your continued use of the Service after the effective date constitutes
        acceptance of the updated policy. If you disagree with material changes you may terminate
        your account before the effective date.
      </p>

      <hr />

      <h2>14. Contact Us</h2>
      <p>
        For any questions, concerns, or requests relating to this Privacy Policy or your personal
        data, please contact:
      </p>
      <address className="not-italic">
        <strong>MiddleDoc Privacy Team</strong><br />
        Email: <a href="mailto:hello@middledoc.com">hello@middledoc.com</a><br />
        Subject line: &ldquo;Privacy Inquiry&rdquo;<br />
        Website: <a href="https://middledoc.com">middledoc.com</a>
      </address>
      <p>
        We aim to respond to all privacy inquiries within 5 business days and to complete data
        subject requests within the legally required timeframe.
      </p>
    </article>
  )
}
