-- Convert all TIMESTAMP columns to TIMESTAMPTZ
ALTER TABLE accountants ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE clients ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE document_requests ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE document_requests ALTER COLUMN updated_at TYPE TIMESTAMPTZ;
ALTER TABLE document_uploads ALTER COLUMN uploaded_at TYPE TIMESTAMPTZ;
ALTER TABLE document_uploads ALTER COLUMN rejected_at TYPE TIMESTAMPTZ;
ALTER TABLE email_reminders ALTER COLUMN sent_at TYPE TIMESTAMPTZ;
ALTER TABLE email_templates ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE email_templates ALTER COLUMN updated_at TYPE TIMESTAMPTZ;
ALTER TABLE teams ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE team_members ALTER COLUMN joined_at TYPE TIMESTAMPTZ;
ALTER TABLE team_invitations ALTER COLUMN expires_at TYPE TIMESTAMPTZ;
ALTER TABLE team_invitations ALTER COLUMN accepted_at TYPE TIMESTAMPTZ;
ALTER TABLE team_invitations ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE client_emails ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE notification_emails ALTER COLUMN created_at TYPE TIMESTAMPTZ;
ALTER TABLE client_assignments ALTER COLUMN assigned_at TYPE TIMESTAMPTZ;

-- Change file_size from INTEGER to BIGINT
ALTER TABLE document_uploads ALTER COLUMN file_size TYPE BIGINT;
